### ISSUE TITLE
Multiple Items on Create Invoice

### ISSUE THREAD

**Issue by brymcg** [privateprep/intacct-ruby#35]
Hi, i've got create invoice working with something like this:

![image](https://user-images.githubusercontent.com/6333380/79367984-f0d3c680-7f0b-11ea-89e6-c16deecacb2b.png)

However, when I try to nest multiple items like so:

![image](https://user-images.githubusercontent.com/6333380/79368032-0517c380-7f0c-11ea-93a9-d41c5bbf7d11.png)

I'm getting a warning about duplicates:

![image](https://user-images.githubusercontent.com/6333380/79368096-19f45700-7f0c-11ea-8140-636f87b1a20f.png)

And it's only writing the last item

Thanks very much

**Comment by lemeo** [comment]
Hey @brymcg, I am also working on the integration with Sage intact in Ruby on Rails. Did you solve this problem? 
And how could we know the object_type? Thank you!

**Comment by danielpowell4** [comment]
It is correct that the `ARINVOICEITEM` key is duplicated in the `ARINVOICEITEMS` hash

have you tried passing an array of hashes instead?

**Comment by lemeo** [comment]
Hey @danielpowell4 Thanks for replying quickly! I will try to using an array for multiple items case!
Another question about the usage.
I want to create [an order entry transaction](https://developer.intacct.com/api/order-entry/order-entry-transactions/#create-order-entry-transaction-legacy:~:text=N8KMSAwIG9iago8PAovVHlwZSAvQ2F0YWxvZwovVmVyc2lvbiAvMS40Ci9QYWdlcyAyIDAgUgo%20...%3C/pdfdata%3E-,Create%20Order%20Entry%20Transaction%20(Legacy),-History), the XML structure like this:
```xml
<function controlid="{{$guid}}">
      <create_sotransaction>
          <transactiontype>Sales Invoice</transactiontype>
          <sotransitems>
              <sotransitem>
                  <itemid>R0001</itemid>
                  <quantity>1</quantity>
              </sotransitem>
              <sotransitem>
                  <itemid>R00002</itemid>
                  <quantity>1</quantity>
              </sotransitem>
          </sotransitems>
          <subtotals>
              <subtotal>
                  <description>Shipping</description>
              </subtotal>
          </subtotals>
      </create_sotransaction>
 </function>
```
^for this case, based on my understanding from the example in [Readme.md](https://github.com/yoshiinc/intacct-ruby/blob/master/README.md) and your suggestion, can I write the request as follows?

```ruby
request.create_sotransaction, parameters: {
  transactiontype: 'Sales Invoice',
  sotransitems: [
      { 
         sotransitem: {
            itemid: 'R0001',
            quantity: '1'
         },
      { 
         sotransitem: {
            itemid: 'R0002',
            quantity: '1'
         }
      }
  ],
   subtotals: { 
      subtotal: {
            description: 'Shipping'
         }
    }
```
^Is it right to remove `object_type` since there is no extra tag needed after the function tag `create_sotransaction`?

**Comment by danielpowell4** [comment]
@lemeo happy to be able to help.

I don't have any working knowledge of the legacy Intacct API as my team only makes use of the "modern" API.

I do think, though, that your above sample should work. Hopefully if it doesn't Intacct responds with a helpful error message!

**Comment by lemeo** [comment]
@danielpowell4 Thanks, Daniel! Let me test and will write down my experience under this ticket.
